apiVersion: apps/v1
kind: Deployment
metadata:
  name: debt-cancel
spec:
  replicas: 2
  selector:
    matchLabels: { app: debt-cancel }
  template:
    metadata:
      labels: { app: debt-cancel }
    spec:
      containers:
        - name: app
          image: YOUR_ECR_URI:latest
          ports: [{ containerPort: 8080 }]
          env:
            - name: APP_CONFIG
              value: -Xms256m -Xmx512m

---
apiVersion: v1
kind: Service
metadata:
  name: debt-cancel-svc
spec:
  type: LoadBalancer
  selector: { app: debt-cancel }
  ports:
    - port: 80
      targetPort: 8080